// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using safeheat_backend_dotnet.Infrastructure.Data.AppData;

#nullable disable

namespace safeheat_backend_dotnet.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("safeheat_backend_dotnet.Domain.Entities.AbrigoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadeAtual")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CapacidadeTotal")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("SH_ABRIGOS");
                });

            modelBuilder.Entity("safeheat_backend_dotnet.Domain.Entities.RegistroDeEntradaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbrigoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("NomePessoa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AbrigoId");

                    b.ToTable("SH_REGISTOS_ENTRADA");
                });

            modelBuilder.Entity("safeheat_backend_dotnet.Domain.Entities.RegistroDeEntradaEntity", b =>
                {
                    b.HasOne("safeheat_backend_dotnet.Domain.Entities.AbrigoEntity", "Abrigo")
                        .WithMany("RegistrosDeEntrada")
                        .HasForeignKey("AbrigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abrigo");
                });

            modelBuilder.Entity("safeheat_backend_dotnet.Domain.Entities.AbrigoEntity", b =>
                {
                    b.Navigation("RegistrosDeEntrada");
                });
#pragma warning restore 612, 618
        }
    }
}
